-- MySQL Script generated by MySQL Workbench
-- Sat Oct 15 12:46:45 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema gfportfolio
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema gfportfolio
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `gfportfolio` DEFAULT CHARACTER SET utf8 ;
-- -----------------------------------------------------
-- Schema new_schema1
-- -----------------------------------------------------
USE `gfportfolio` ;

-- -----------------------------------------------------
-- Table `gfportfolio`.`locations`
-- -----------------------------------------------------

CREATE TABLE IF NOT EXISTS `gfportfolio`.`locations` (
  `id` INT NOT NULL,
  `location` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gfportfolio`.`projects`
-- -----------------------------------------------------

CREATE TABLE IF NOT EXISTS `gfportfolio`.`projects` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `img` VARCHAR(100) NOT NULL,
  `description` TEXT(250) NOT NULL,
  `locations_id` INT NOT NULL,
  PRIMARY KEY (`id`, `locations_id`),
  CONSTRAINT `fk_projects_locations`
    FOREIGN KEY (`locations_id`)
    REFERENCES `gfportfolio`.`locations` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_projects_locations_idx` ON `gfportfolio`.`projects` (`locations_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `gfportfolio`.`skills`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gfportfolio`.`skills` ;

CREATE TABLE IF NOT EXISTS `gfportfolio`.`skills` (
  `id` INT NOT NULL,
  `skill` VARCHAR(45) NOT NULL,
  `img` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gfportfolio`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gfportfolio`.`users` ;

CREATE TABLE IF NOT EXISTS `gfportfolio`.`users` (
  `id` INT NOT NULL,
  `nameLastname` VARCHAR(145) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `mesaje` TEXT(300) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gfportfolio`.`projects_skills`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gfportfolio`.`projects_skills` ;

CREATE TABLE IF NOT EXISTS `gfportfolio`.`projects_skills` (
  `projects_id` INT NOT NULL,
  `projects_locations_id` INT NOT NULL,
  `skills_id` INT NOT NULL,
  PRIMARY KEY (`projects_id`, `projects_locations_id`, `skills_id`),
  CONSTRAINT `fk_projects_has_skills_projects1`
    FOREIGN KEY (`projects_id` , `projects_locations_id`)
    REFERENCES `gfportfolio`.`projects` (`id` , `locations_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_projects_has_skills_skills1`
    FOREIGN KEY (`skills_id`)
    REFERENCES `gfportfolio`.`skills` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_projects_has_skills_skills1_idx` ON `gfportfolio`.`projects_skills` (`skills_id` ASC) VISIBLE;

CREATE INDEX `fk_projects_has_skills_projects1_idx` ON `gfportfolio`.`projects_skills` (`projects_id` ASC, `projects_locations_id` ASC) VISIBLE;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
